package me.realimpact.dummy.swing.service;

import me.realimpact.dummy.swing.dto.ReqRelMobilePhoneAndOlmagoCustDto;
import me.realimpact.dummy.swing.dto.MobilePhoneAndOlmagoRelationResponseDto;

public interface OlmagoService {
  MobilePhoneAndOlmagoRelationResponseDto linkOlmagoCustomerWithMobilePhoneService(ReqRelMobilePhoneAndOlmagoCustDto reqRelMobilePhoneAndOlmagoCustDto);
  MobilePhoneAndOlmagoRelationResponseDto unlinkOlmagoCustomerWithMobilePhoneService(ReqRelMobilePhoneAndOlmagoCustDto reqRelMobilePhoneAndOlmagoCustDto);
}
